spring:
   profiles: local
   datasource:
      jdbc-url: jdbc:log4jdbc:postgresql://192.168.30.19:5432/db_stock
      username: yapdev
      password: yaproqkf
   driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy